[tasks.watch-app]
script = '''
cargo build --release --target wasm32-unknown-unknown --bin app
wasm-bindgen --target web --no-typescript --out-name app target/wasm32-unknown-unknown/release/app.wasm --out-dir ./static
'''
watch = { ignore_pattern = "static/*" }

[tasks.watch-worker]
script = '''
cargo build --release --target wasm32-unknown-unknown --bin worker
wasm-bindgen --target no-modules --no-typescript --out-name worker target/wasm32-unknown-unknown/release/worker.wasm --out-dir ./static
'''
watch = { ignore_pattern = "static/*" }

[tasks.release]
command = "wasm-pack"
args = ["build", "--release", "--target", "web", "--out-name", "wasm", "--out-dir", "./static"]
watch = { ignore_pattern = "static/*" }

[tasks.serve]
command = "python3"
args = ["-m", "http.server", "--directory", "./static/", "3000"]

[tasks.sass]
command = "sass"
args = ["--watch", "styles:static/css"]