[tasks.build]
command = "wasm-pack"
args = ["build", "--dev", "--target", "web", "--out-name", "app", "--out-dir", "./static", "--", "--bin", "app"]
watch = { ignore_pattern = "static/*" }

[tasks.build-worker]
command = "wasm-pack"
args = ["build", "--dev", "--target", "no-modules", "--out-name", "worker", "--out-dir", "./static", "--", "--bin", "worker"]
watch = { ignore_pattern = "static/*" }

[tasks.release]
command = "wasm-pack"
args = ["build", "--release", "--target", "web", "--out-name", "wasm", "--out-dir", "./static"]
watch = { ignore_pattern = "static/*" }

[tasks.serve]
command = "python3"
args = ["-m", "http.server", "--directory", "./static/", "3000"]

[tasks.sass]
command = "sass"
args = ["--watch", "styles:static/css"]